### ISSUE TITLE
Nil access panic 

### ISSUE THREAD

**Issue by yarinm** [kubernetes-sigs/azuredisk-csi-driver#1376]
**What happened**:

Controller crashes during attach / detach:

```
csi-controller panic: runtime error: invalid memory address or nil pointer dereference
csi-controller [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x160dee6]
csi-controller
csi-controller goroutine 119 [running]:
csi-controller sigs.k8s.io/cloud-provider-azure/pkg/provider/virtualmachine.FromVirtualMachineScaleSetVM(0xc000790270, 0x18573c0)
csi-controller     /go/src/github.com/kubernetes-sigs/azuredisk-csi-driver/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/virtualmachine/virtualmachine.go:107 +0x26
csi-controller sigs.k8s.io/cloud-provider-azure/pkg/provider.(*ScaleSet).getVmssVMByNodeIdentity.func1({0xc00047e540, 0x21}, 0x29)
csi-controller     /go/src/github.com/kubernetes-sigs/azuredisk-csi-driver/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go:173 +0xd0
csi-controller sigs.k8s.io/cloud-provider-azure/pkg/provider.(*ScaleSet).getVmssVMByNodeIdentity(0xc000250a40, 0xc000234e10, 0x21)
csi-controller     /go/src/github.com/kubernetes-sigs/azuredisk-csi-driver/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go:185 +0x11a
csi-controller sigs.k8s.io/cloud-provider-azure/pkg/provider.(*ScaleSet).getVmssVM(0x0, {0xc00047e540, 0x21}, 0x0)
csi-controller     /go/src/github.com/kubernetes-sigs/azuredisk-csi-driver/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go:226 +0x4b
csi-controller sigs.k8s.io/cloud-provider-azure/pkg/provider.(*ScaleSet).GetInstanceIDByNodeName(0xc000250a40, {0xc00047e540, 0x21})
csi-controller     /go/src/github.com/kubernetes-sigs/azuredisk-csi-driver/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go:361 +0x12a
csi-controller sigs.k8s.io/cloud-provider-azure/pkg/provider.(*Cloud).InstanceID(0xc00033e400, {0x15a, 0x1a2}, {0xc00047e540, 0x21})
csi-controller     /go/src/github.com/kubernetes-sigs/azuredisk-csi-driver/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_instances.go:376 +0x1ff
csi-controller sigs.k8s.io/cloud-provider-azure/pkg/provider.(*controllerCommon).DetachDisk(0xc0002f81c0, {0x1e03a78, 0xc000234570}, {0xc00014432f, 0x4f}, {0xc0001442a0, 0xde}, {0xc00047e540, 0x21})
csi-controller     /go/src/github.com/kubernetes-sigs/azuredisk-csi-driver/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go:312 +0x8c
csi-controller sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk.(*Driver).ControllerUnpublishVolume(0xc000146160, {0x1e03a78, 0xc000234570}, 0x228be16)
csi-controller     /go/src/github.com/kubernetes-sigs/azuredisk-csi-driver/pkg/azuredisk/controllerserver.go:462 +0x457
csi-controller github.com/container-storage-interface/spec/lib/go/csi._Controller_ControllerUnpublishVolume_Handler.func1({0x1e03a78, 0xc000234570}, {0x1a8dae0, 0xc00007c870})
csi-controller     /go/src/github.com/kubernetes-sigs/azuredisk-csi-driver/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:5730 +0x78
csi-controller sigs.k8s.io/azuredisk-csi-driver/pkg/csi-common.logGRPC({0x1e03a78, 0xc000234570}, {0x1a8dae0, 0xc00007c870}, 0xc00007a7a0, 0xc000182f60)
csi-controller     /go/src/github.com/kubernetes-sigs/azuredisk-csi-driver/pkg/csi-common/utils.go:80 +0x3b2
csi-controller github.com/container-storage-interface/spec/lib/go/csi._Controller_ControllerUnpublishVolume_Handler({0x1b75680, 0xc000146160}, {0x1e03a78, 0xc000234570}, 0xc0003fc1e0, 0x1c76b40)
csi-controller     /go/src/github.com/kubernetes-sigs/azuredisk-csi-driver/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:5732 +0x138
csi-controller google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004d8540, {0x1e32190, 0xc00027a180}, 0xc0006985a0, 0xc0000c2f60, 0x2de6c88, 0x0)
csi-controller     /go/src/github.com/kubernetes-sigs/azuredisk-csi-driver/vendor/google.golang.org/grpc/server.go:1282 +0xccf
csi-controller google.golang.org/grpc.(*Server).handleStream(0xc0004d8540, {0x1e32190, 0xc00027a180}, 0xc0006985a0, 0x0)
csi-attacher k8s.io/klog/v2.(*loggingT).printf(0x246fa00, 0xc000000000, 0x0, 0x0, 0x0, 0x0, 0x187e28a, 0x19, 0xc000e46750, 0x1, ...)
csi-attacher     /home/travis/gopath/src/github.com/kubernetes-csi/external-attacher/vendor/k8s.io/klog/v2/klog.go:750 +0x191
csi-attacher k8s.io/klog/v2.Verbose.Infof(...)
csi-attacher     /home/travis/gopath/src/github.com/kubernetes-csi/external-attacher/vendor/k8s.io/klog/v2/klog.go:1354
csi-attacher github.com/kubernetes-csi/external-attacher/pkg/controller.(*csiHandler).saveAttachError(0xc0002cc240, 0xc00070af78, 0x1a3a440, 0xc00000e438, 0x1a3a440, 0xc00000e438, 0x186e9e6)
csi-attacher     /home/travis/gopath/src/github.com/kubernetes-csi/external-attacher/pkg/controller/csi_handler.go:585 +0x4b3
csi-attacher github.com/kubernetes-csi/external-attacher/pkg/controller.(*csiHandler).syncAttach(0xc0002cc240, 0xc00070af78, 0x0, 0x0)
csi-controller     /go/src/github.com/kubernetes-sigs/azuredisk-csi-driver/vendor/google.golang.org/grpc/server.go:1616 +0xa2a
csi-controller google.golang.org/grpc.(*Server).serveStreams.func1.2()
csi-controller     /go/src/github.com/kubernetes-sigs/azuredisk-csi-driver/vendor/google.golang.org/grpc/server.go:921 +0x98
csi-controller created by google.golang.org/grpc.(*Server).serveStreams.func1
csi-controller     /go/src/github.com/kubernetes-sigs/azuredisk-csi-driver/vendor/google.golang.org/grpc/server.go:919 +0x294
```

I'm also seeing these info logs which might be relevant:
```
csi-controller I0612 06:10:57.000546       1 azure_vmss_cache.go:206] VMSS virtualMachine "aks-analysis1-47840137-vmss0006xm" is under deleting, setting its cache to nil
csi-controller I0612 06:10:57.000582       1 azure_vmss_cache.go:206] VMSS virtualMachine "aks-analysis1-47840137-vmss0006xn" is under deleting, setting its cache to nil
csi-controller I0612 06:10:57.000589       1 azure_vmss_cache.go:206] VMSS virtualMachine "aks-analysis1-47840137-vmss0006xo" is under deleting, setting its cache to nil
csi-controller I0612 06:10:57.000595       1 azure_vmss_cache.go:206] VMSS virtualMachine "aks-analysis1-47840137-vmss0006xp" is under deleting, setting its cache to nil
csi-controller I0612 06:10:57.000602       1 azure_vmss_cache.go:206] VMSS virtualMachine "aks-analysis1-47840137-vmss0006xq" is under deleting, setting its cache to nil
csi-controller I0612 06:10:57.000608       1 azure_vmss_cache.go:206] VMSS virtualMachine "aks-analysis1-47840137-vmss0006xr" is under deleting, setting its cache to nil
csi-controller I0612 06:10:57.000615       1 azure_vmss_cache.go:206] VMSS virtualMachine "aks-analysis1-47840137-vmss0006xs" is under deleting, setting its cache to nil
csi-controller I0612 06:10:57.000622       1 azure_vmss_cache.go:206] VMSS virtualMachine "aks-analysis1-47840137-vmss0006xt" is under deleting, setting its cache to nil
csi-controller I0612 06:10:57.000629       1 azure_vmss_cache.go:206] VMSS virtualMachine "aks-analysis1-47840137-vmss0006xu" is under deleting, setting its cache to nil
csi-controller I0612 06:10:57.000636       1 azure_vmss_cache.go:206] VMSS virtualMachine "aks-analysis1-47840137-vmss00075f" is under deleting, setting its cache to nil
csi-controller I0612 06:10:57.000648       1 azure_vmss_cache.go:206] VMSS virtualMachine "aks-analysis1-47840137-vmss00075g" is under deleting, setting its cache to nil
csi-controller I0612 06:10:57.000659       1 azure_vmss_cache.go:206] VMSS virtualMachine "aks-analysis1-47840137-vmss00075h" is under deleting, setting its cache to nil
```

This happens when the VMSS is under fault in Azure due to "Internal disk error"

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: 1.15
- Kubernetes version (use `kubectl version`): 1.21.7

**Comment by andyzhangx** [comment]
thanks for reporting, this issue is fixed in v1.17.0: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/v1.17.0/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go#L172-L175
