### ISSUE TITLE
[V2] az-log panics when getting the controller logs

### ISSUE THREAD

**Issue by edreed** [kubernetes-sigs/azuredisk-csi-driver#1527]
**What happened**:

`az-log` panics when getting the controller logs:

```log
panic: leases.coordination.k8s.io "default" not found
goroutine 1 [running]:
sigs.k8s.io/azuredisk-csi-driver/cmd/az-log/cmd.GetLeaderControllerPod({0x1a61840, 0xc000312000})
        /home/jlong/azuredisk-csi-driver/cmd/az-log/cmd/controller.go:69 +0x385
sigs.k8s.io/azuredisk-csi-driver/cmd/az-log/cmd.glob..func1(0x25a2c80?, {0x1805b2c?, 0x2?, 0x2?})
        /home/jlong/azuredisk-csi-driver/cmd/az-log/cmd/controller.go:43 +0xe5
github.com/spf13/cobra.(*Command).execute(0x25a2c80, {0xc000357b40, 0x2, 0x2})
        /home/jlong/azuredisk-csi-driver/vendor/github.com/spf13/cobra/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0x25a3900)
        /home/jlong/azuredisk-csi-driver/vendor/github.com/spf13/cobra/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/jlong/azuredisk-csi-driver/vendor/github.com/spf13/cobra/command.go:918
sigs.k8s.io/azuredisk-csi-driver/cmd/az-log/cmd.Execute()
        /home/jlong/azuredisk-csi-driver/cmd/az-log/cmd/root.go:43 +0x25
main.main()
        /home/jlong/azuredisk-csi-driver/cmd/az-log/main.go:22 +0x17


goroutine 41 [IO wait]:
internal/poll.runtime_pollWait(0x7fe060619678, 0x72)
        /usr/local/go/src/runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0xc00037e880?, 0xc000594a80?, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00037e880, {0xc000594a80, 0xa80, 0xa80})
        /usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc00037e880, {0xc000594a80?, 0xc00013ba60?, 0xc000594b67?})
        /usr/local/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000014008, {0xc000594a80?, 0x50000c0004b17e0?, 0x40f4e7?})
        /usr/local/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc00012e258, {0xc000594a80?, 0x0?, 0x6fa1f9?})
        /usr/local/go/src/crypto/tls/conn.go:787 +0x3d
bytes.(*Buffer).ReadFrom(0xc0003c85f8, {0x1a38360, 0xc00012e258})
        /usr/local/go/src/bytes/buffer.go:202 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0003c8380, {0x1a3b9e0?, 0xc000014008}, 0x99e?)
        /usr/local/go/src/crypto/tls/conn.go:809 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc0003c8380, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:616 +0x116
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:582
crypto/tls.(*Conn).Read(0xc0003c8380, {0xc00053c000, 0x1000, 0xa8e2a0?})
        /usr/local/go/src/crypto/tls/conn.go:1287 +0x16f
bufio.(*Reader).Read(0xc0002da060, {0xc00015c2e0, 0x9, 0xa9c5c5?})
        /usr/local/go/src/bufio/bufio.go:237 +0x1bb
io.ReadAtLeast({0x1a38200, 0xc0002da060}, {0xc00015c2e0, 0x9, 0x9}, 0x9)
        /usr/local/go/src/io/io.go:332 +0x9a
io.ReadFull(...)
        /usr/local/go/src/io/io.go:351
golang.org/x/net/http2.readFrameHeader({0xc00015c2e0?, 0x9?, 0xc001590330?}, {0x1a38200?, 0xc0002da060?})
        /home/jlong/azuredisk-csi-driver/vendor/golang.org/x/net/http2/frame.go:237 +0x6e
golang.org/x/net/http2.(*Framer).ReadFrame(0xc00015c2a0)
        /home/jlong/azuredisk-csi-driver/vendor/golang.org/x/net/http2/frame.go:498 +0x95
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc0004b1f98)
        /home/jlong/azuredisk-csi-driver/vendor/golang.org/x/net/http2/transport.go:2118 +0x130
golang.org/x/net/http2.(*ClientConn).readLoop(0xc000140480)
        /home/jlong/azuredisk-csi-driver/vendor/golang.org/x/net/http2/transport.go:2014 +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
        /home/jlong/azuredisk-csi-driver/vendor/golang.org/x/net/http2/transport.go:725 +0xaaa
```

**What you expected to happen**:

It should return the log for the current leader.

**How to reproduce it**:

**Anything else we need to know?**:

`az-log` assumes the lease name for the CSI controller is "default" which is no longer true. The current default value is `csi-azuredisk-controller` but can be overridden through the `--controller-partition` command-line flag or the `AzDriverConfiguration.ControllerConfig.PartitionName` configuration value. The lease is in the namespace defined by the `--leader-election-namespace` command-line flag or the `AzDriverConfiguration.ControllerConfig.LeaderElectionNamespace` configuration value.

The change was made by PR #1363.

**Environment**:

- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jmclong** [comment]
Additionally, the lease is in the "kube-system" namespace (at least by default). The code is looking in the `consts.DefaultAzureDiskCrdNamespace` namespace.

**Comment by jmclong** [comment]
Hi Huichan,

I substituted the following in `GetLeaderControllerPod` to get things working against the default values:

```go
func GetLeaderControllerPod(clientsetK8s kubernetes.Interface) *v1.Pod {
	//Get node that leader controller pod is running in
	lease, err := clientsetK8s.CoordinationV1().Leases(GetReleaseNamespace()).Get(context.Background(), "csi-azuredisk-controller", metav1.GetOptions{})
	if err != nil {
		panic(err.Error())
	}
	holder := *lease.Spec.HolderIdentity
	node := strings.Split(holder, "_")[0]

	// Get pod name of the leader controller
	pods, err := clientsetK8s.CoreV1().Pods(GetReleaseNamespace()).List(context.Background(), metav1.ListOptions{
		FieldSelector: "spec.nodeName=" + node,
		LabelSelector: "app=" + GetDriverInstallationType() + "-controller",
	})
	if err != nil {
		panic(err.Error())
	}
	if len(pods.Items) != 1 {
		fmt.Println("zero or more than one controller plugins were found")
		os.Exit(0)
	}

	return &pods. Items[0]
}

```

**Comment by hccheng72** [comment]
@jmclong Thanks for your comments.
