### ISSUE TITLE
`node.allowEmptyCloudConfig` not working

### ISSUE THREAD

**Issue by jkbschmid** [kubernetes-sigs/azuredisk-csi-driver#1696]
Hello 👋 ,

I've deployed azuredisk-driver v1.26.1 to a self-hosted cluster and I'm having issues with the `node.allowEmptyCloudConfig` option.

I'm trying to run `csi-azuredisk-node`  without azure credentials. The driver logs `driver will run without cloud config`, but panics a short while later (see below).
Is the `--allow-empty-cloud-config` flag still supported?

Thank you! 🙂 

**What happened**:

`csi-azuredisk-node` panics and crashes, although it runs with `--allow-empty-cloud-config=true`:
```
Streaming logs below:
I0120 16:10:25.158722       1 azuredisk.go:175] driver userAgent: disk.csi.azure.com/v1.26.1 OSS-helm
I0120 16:10:25.159229       1 azure_disk_utils.go:162] reading cloud config from secret kube-system/azure-cloud-provider
I0120 16:10:25.166206       1 azure_disk_utils.go:169] InitializeCloudFromSecret: failed to get cloud config from secret kube-system/azure-cloud-provider: failed to get secret kube-system/azure-cloud-provider: secrets "azure-cloud-provider" not found
I0120 16:10:25.166219       1 azure_disk_utils.go:174] could not read cloud config from secret kube-system/azure-cloud-provider
I0120 16:10:25.166224       1 azure_disk_utils.go:184] use default AZURE_CREDENTIAL_FILE env var: /etc/kubernetes/azure.json
W0120 16:10:25.166244       1 azure_disk_utils.go:189] load azure config from file(/etc/kubernetes/azure.json) failed with open /etc/kubernetes/azure.json: no such file or directory
I0120 16:10:25.166249       1 azure_disk_utils.go:201] no cloud config provided, error: failed to get secret kube-system/azure-cloud-provider: secrets "azure-cloud-provider" not found, driver will run without cloud config
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x17e22c7]

goroutine 1 [running]:
sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk.(*Driver).Run(0xc0005aa9a0, {0x7ffd7936dc22, 0x14}, {0x0, 0x0}, 0x0, 0x0?)
    /mnt/vss/_work/1/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk/azuredisk.go:213 +0xac7
main.handle()
    /mnt/vss/_work/1/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azurediskplugin/main.go:116 +0x272
main.main()
    /mnt/vss/_work/1/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azurediskplugin/main.go:84 +0x1da
```

**What you expected to happen**:

`csi-azuredisk-node`  runs correctly even when there is no cloud config provided.

**How to reproduce it**:

Don't specify a cloud config secret or file and run `csi-azuredisk-node` with `--allow-empty-cloud-config`.
**Anything else we need to know?**:

**Environment**:
```
DRIVER INFORMATION:
-------------------
Build Date: "2023-01-12T07:14:08Z"
Compiler: gc
Driver Name: disk.csi.azure.com
Driver Version: v1.26.1
Git Commit: c33a3812e920a1ef3fef5c95d63d27d5a78bdce2
Go Version: go1.19.1
Platform: linux/amd64
Topology Key: topology.disk.csi.azure.com/zone
```

**Comment by andyzhangx** [comment]
@jkbschmid pls try with v1.26.2 version, it has fixed the issue, thanks.
