### ISSUE TITLE
[V2] Controller sometimes panics while trying to get the node instance type

### ISSUE THREAD

**Issue by edreed** [kubernetes-sigs/azuredisk-csi-driver#1697]
**What happened**:

The controller is panics in `cloud-provider-azure` during the `pull-azuredisk-csi-driver-e2e-single-az` test.

```log
I0120 17:40:12.382904       1 azuredisk_v2.go:248] disable UseInstanceMetadata for controller
I0120 17:40:12.382917       1 azuredisk_v2.go:264] cloud: AzurePublicCloud, location: northeurope, rg: kubetest-yfm8kdjb, VMType: standard, PrimaryScaleSetName: , PrimaryAvailabilitySetName: agentpool1-availabilitySet-36733010, DisableAvailabilitySetNodes: false
I0120 17:40:12.382926       1 skus.go:123] NewNodeInfo: Starting to populate node and disk sku information.
I0120 17:40:12.578924       1 util.go:124] Send.sendRequest got response with ContentLength -1, StatusCode 200 and responseBody length 18064
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x185b4a7]

goroutine 1 [running]:
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*availabilitySet).GetInstanceTypeByNodeName(0x0?, {0x0, 0x0})
	/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go:591 +0xc7
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*Cloud).InstanceType(0xc0000bca80, {0x0?, 0x2040294?}, {0x0, 0x0})
	/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_instances.go:476 +0x10b
sigs.k8s.io/azuredisk-csi-driver/pkg/optimization.NewNodeInfo({0x22ec008, 0xc000118000}, {0x22f5298, 0xc0000bca80}, {0x0, 0x0})
	/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/optimization/skus.go:130 +0xc5
sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk.(*DriverV2).Run(0xc000003900, {0xc000149350, 0x14}, {0x22c7e70, 0x0}, 0x0, 0xaf?)
	/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk/azuredisk_v2.go:270 +0x1a59
main.handle()
	/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azurediskplugin/main.go:124 +0xd0
main.main()
	/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azurediskplugin/main.go:107 +0x1d5
```

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:

- CSI Driver version: latest-v2
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by edreed** [comment]
I am not sure why we are only just now seeing this panic, but the controller should call `optimization.NewNodeInfo()` since that is for node-specific disk I/O optimization support.

**Comment by hccheng72** [comment]
I saw `pull-azuredisk-csi-driver-e2e-single-az` also failed in my other PR due to failed installation yesterday. It passed after a few times of retest.
