### ISSUE TITLE
add expand volume integration test

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#469]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

```
>git diff run-test.sh
diff --git a/test/integration/run-test.sh b/test/integration/run-test.sh
index 0442ae9d..b9b501ac 100755
--- a/test/integration/run-test.sh
+++ b/test/integration/run-test.sh
@@ -63,6 +63,10 @@ echo "Got volume id: $volumeid"

 "$CSC_BIN" controller validate-volume-capabilities --endpoint "$endpoint" --cap 1,block "$volumeid"

+echo 'Expand volume test:'
+"$CSC_BIN" controller expand-volume --endpoint "$endpoint" --cap 1,block "$volumeid" --req-bytes 21474836480
+sleep 30
+
 echo 'Attach volume test:'
 "$CSC_BIN" controller publish --endpoint "$endpoint" --node-id "$node" --cap 1,block "$volumeid"
 sleep 20
```

 - got following error related to vol cap setting:
```
# csc controller expand-volume --endpoint tcp://127.0.0.1:10000 --cap 1,block "/subscriptions/xxx/resourceGroups/mc_andy-aks1147_andy-aks1147_eastus/providers/Microsoft.Compute/disks/CSIVolumeName2" --req-bytes 214748364800    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8507d0]

goroutine 1 [running]:
github.com/rexray/gocsi/csc/cmd.(*volumeCapabilitySliceArg).Set(0x0, 0x7ffe3914d39e, 0x7, 0x3, 0xc000105818)
        /root/go/src/github.com/rexray/gocsi/csc/cmd/vartypes.go:96 +0x5d0
github.com/spf13/pflag.(*FlagSet).Set(0xc00017c4b0, 0x96e086, 0x3, 0x7ffe3914d39e, 0x7, 0x7ffe3914d39a, 0xc000105790)
        /root/go/pkg/mod/github.com/spf13/pflag@v1.0.0/flag.go:432 +0xe3
github.com/spf13/pflag.(*FlagSet).Parse.func1(0xc000196960, 0x7ffe3914d39e, 0x7, 0x3, 0xc000105818)
        /root/go/pkg/mod/github.com/spf13/pflag@v1.0.0/flag.go:1028 +0x54
github.com/spf13/pflag.(*FlagSet).parseLongArg(0xc00017c4b0, 0x7ffe3914d398, 0x5, 0xc00018f6f0, 0x4, 0x4, 0xc00016fd00, 0xc00018f6e0, 0x5, 0x5, ...)
        /root/go/pkg/mod/github.com/spf13/pflag@v1.0.0/flag.go:914 +0x279
github.com/spf13/pflag.(*FlagSet).parseArgs(0xc00017c4b0, 0xc00018f6f0, 0x4, 0x4, 0xc00016fd00, 0x834610, 0xc00017c4b0)
        /root/go/pkg/mod/github.com/spf13/pflag@v1.0.0/flag.go:1003 +0x49c
github.com/spf13/pflag.(*FlagSet).Parse(0xc00017c4b0, 0xc00018f6c0, 0x7, 0x7, 0x0, 0xc000024860)
        /root/go/pkg/mod/github.com/spf13/pflag@v1.0.0/flag.go:1031 +0xc7
github.com/spf13/cobra.(*Command).ParseFlags(0xdada80, 0xc00018f6c0, 0x7, 0x7, 0xc0000200b0, 0x9)
        /root/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:1368 +0x9b
github.com/spf13/cobra.(*Command).execute(0xdada80, 0xc00018f6c0, 0x7, 0x7, 0xdada80, 0xc00018f6c0)
        /root/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:645 +0x8f
github.com/spf13/cobra.(*Command).ExecuteC(0xdb0720, 0x1, 0x9902cb, 0x13b)
        /root/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:783 +0x2c9
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:736
github.com/rexray/gocsi/csc/cmd.Execute()
        /root/go/src/github.com/rexray/gocsi/csc/cmd/root.go:165 +0x3f
main.main()
        /root/go/src/github.com/rexray/gocsi/csc/main.go:6 +0x20

```
**Describe alternatives you've considered**

**Additional context**

**Comment by sunpa93** [comment]
The abovementioned error from expand-volume-test should be resolved upon approval of the PR below:
https://github.com/rexray/gocsi/pull/142

I will submit a PR that adds an expand volume test to the integration test once the gocsi PR is accepted.
